### ISSUE TITLE
Variable Interpolation?

### ISSUE THREAD

**Issue by Apestein** [rehype-pretty/rehype-pretty-code#173]
```tsx
import { Code } from "./code"

const rawCode = `
\`\`\`tsx
export default function Foo() {
  return (
    <p>foo</p>
  )
}
\`\`\`
`

export function ComponentPreview({
  Component,
  code,
}: {
  Component: () => JSX.Element
  code: string
}) {
  const rawCode2 = `
  \`\`\`tsx
  ${code}
  \`\`\`
  `

  return (
    <div className="space-y-3">
      <Component />
      <Code code={rawCode} />
      <Code code={rawCode2} />
      <pre>{code}</pre>
    </div>
  )
}
```

Anyway to to use variable interpolation? rawCode is properly formatted but rawCode2 is not. When I use `pre` with `${code}` you can see that `code` is properly formatted. From [next.js RSC example](https://github.com/rehype-pretty/rehype-pretty-code/blob/master/website/src/app/rsc/page.tsx).
![Screenshot (109)](https://github.com/rehype-pretty/rehype-pretty-code/assets/107362680/41c88063-3d56-4985-9638-676a1e2603b7)

**Comment by atomiks** [comment]
Try using https://www.npmjs.com/package/dedent

**Comment by Apestein** [comment]
> Try using https://www.npmjs.com/package/dedent

Dedent didn't work but I tried something else and it worked but now there is a new problem.
```tsx
import { Code } from "./code"
import dedent from "dedent"

const rawCode = `
\`\`\`tsx
export default function Foo() {
  return <p>foo</p> 
}
\`\`\`
`

export function ComponentPreview({
  Component,
  code,
}: {
  Component: () => JSX.Element
  code: string
}) {
  const rawCode2 = "```tsx\n" + code + "```"
  return (
    <div className="space-y-3">
      <Component />
      <Code code={rawCode} />
      <Code code={rawCode2} />
      <pre>{rawCode2}</pre>
    </div>
  )
}
```
![Screenshot (110)](https://github.com/rehype-pretty/rehype-pretty-code/assets/107362680/c62206d9-9457-4b45-a45c-aa1d5a8044c0)

There is something wrong with how the library is parsing the strings, because `pre` works perfectly fine. The behavior should be like `pre`.

**Comment by atomiks** [comment]
This has no issues in the [`/rsc` folder](https://github.com/rehype-pretty/rehype-pretty-code/blob/5535ddbb6e1774598ccef1e8c29a6c357305141a/website/src/app/rsc/page.tsx#L44) in this repo's `/website`:

```js
import * as React from 'react';
import { Code } from '@/app/code';

const test = `export function Comp1() {
  return <p>Comp1</p>;
}`;

function Preview({ code }: { code: string }) {
  const raw = `\`\`\`tsx\n${code}\n\`\`\``;
  return <Code code={raw} />;
}

export default async function ServerComponentPage() {
  return <Preview code={test} />;
}
```


Can you show the callsite of `<ComponentPreview>`? How are you passing the string to the `code` prop?

**Comment by Apestein** [comment]
> This has no issues in the [`/rsc` folder](https://github.com/rehype-pretty/rehype-pretty-code/blob/5535ddbb6e1774598ccef1e8c29a6c357305141a/website/src/app/rsc/page.tsx#L44) in this repo's `/website`:
> 
> ```js
> import * as React from 'react';
> import { Code } from '@/app/code';
> 
> const test = `export function Comp1() {
>   return <p>Comp1</p>;
> }`;
> 
> function Preview({ code }: { code: string }) {
>   const raw = `\`\`\`tsx\n${code}\n\`\`\``;
>   return <Code code={raw} />;
> }
> 
> export default async function ServerComponentPage() {
>   return <Preview code={test} />;
> }
> ```
> 
> Can you show the callsite of `<ComponentPreview>`? How are you passing the string to the `code` prop?

All that matters is that the code comes in properly formatted. It doesn't matter how I'm passing in the string. I know the code is properly formatted because it works with `pre` and by console.log. I went ahead and put it in a repo so you can see for yourself.

https://github.com/Apestein/next-mdx-demo/blob/main/app/component-demo/%5Bslug%5D/page.tsx

**Comment by atomiks** [comment]
I don't see any formatting issues on my side:

http://localhost:3000/component-demo/code

<img width="451" alt="Screenshot 2024-02-03 at 11 00 18 AM" src="https://github.com/rehype-pretty/rehype-pretty-code/assets/22450188/1841cf7c-d99b-4330-874f-3e44c5613180">

---

Try investigating the CSS in DevTools and see what's causing the gap for you? I don't understand why it would be happening.

**Comment by Apestein** [comment]
> I don't see any formatting issues on my side:
> 
> http://localhost:3000/component-demo/code
> 
> <img alt="Screenshot 2024-02-03 at 11 00 18 AM" width="451" src="https://private-user-images.githubusercontent.com/22450188/301997731-1841cf7c-d99b-4330-874f-3e44c5613180.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MjUyNzMsIm5iZiI6MTcwNjkyNDk3MywicGF0aCI6Ii8yMjQ1MDE4OC8zMDE5OTc3MzEtMTg0MWNmN2MtZDk5Yi00MzMwLTg3NGYtM2U0NGM1NjEzMTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDAxNDkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNWFjMzBmYzFmYmJiZjQwMjVmOTI1OTg4MmZlMmM5MWZhNGIyNDcwYmNiZTcxZDc2NGZkZjRiMWRmZDM2YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eEAL35xJGOXxhLfhHsITDBkNaFk8KU81URWW5C7fNKE">
> Try investigating the CSS in DevTools and see what's causing the gap for you? I don't understand why it would be happening.

So it worked without you changing anything?
![Screenshot (111)](https://github.com/rehype-pretty/rehype-pretty-code/assets/107362680/8cead7f8-e03c-441c-85b8-c8b0f7bb34d8)
As you can see, gaps are just <span> with a one space it seems. I should mention I'm on windows also, I don't see how this can be possible either.

**Comment by atomiks** [comment]
Yeah I just did fresh clone/install with `npm i` and had no gaps. I think that bug _could_ be related to `grid: true` option. If you pass `grid: false` in the `rehypePrettyCode` options, do they disappear?

I don't understand why it doesn't happen for me though. Maybe different dependencies versions? Have you tried a fresh install?

**Comment by Apestein** [comment]
> Yeah I just did fresh clone/install with `npm i` and had no gaps. I think that bug _could_ be related to `grid: true` option. If you pass `grid: false` in the `rehypePrettyCode` options, do they disappear?
> 
> I don't understand why it doesn't happen for me though. Maybe different dependencies versions? Have you tried a fresh install?

`grid: false` didn't do anything. And yes, I just deleted the whole app and clone it again. Didn't fix. 😕

**Comment by atomiks** [comment]
Maybe Node.js version? I'm using v20.10.0.

**Comment by atomiks** [comment]
Ugh hang on. I definitely think it's a Windows vs. Mac thing. Windows has different behavior for line breaks I think. 

```js
const fileContent = fs.readFileSync(filePath, "utf8")
```

Try replacing `\r` or something here with `\n` or removing unnecessary breaks?

**Comment by Apestein** [comment]
> Ugh hang on. I definitely think it's a Windows vs. Mac thing. Windows has different behavior for line breaks I think.
> 
> ```js
> const fileContent = fs.readFileSync(filePath, "utf8")
> ```
> 
> Try replacing `\r` or something here with `\n` or removing unnecessary breaks?

Definitely a windows thing, I just switch over to linux and now it's working.

**Comment by Apestein** [comment]
Can't seem to fix it on windows no matter what I try though. Thanks for your help anyways.
