### ISSUE TITLE
problem when use 'CRLF' as line breaks in mdx file

### ISSUE THREAD

**Issue by dreamerx0** [rehype-pretty/rehype-pretty-code#180]
In windows when using 'CRLF' as line breaks in mdx file, there will be additional empty line in code block. it's ok when using 'LF' as line breaks. 

![image](https://github.com/rehype-pretty/rehype-pretty-code/assets/45530687/b19b425e-5fcd-4aac-8ff4-13e3a5b6f17b)

![image](https://github.com/rehype-pretty/rehype-pretty-code/assets/45530687/83a92a98-a79a-4a62-8eda-47b335216a62)

**Comment by o-az** [comment]
Can you share a stackblitz repro?
