### ISSUE TITLE
rehypePrettyCode typings became incompatible with Astro v4

### ISSUE THREAD

**Issue by bennycode** [rehype-pretty/rehype-pretty-code#194]
When I upgraded my Astro site from Astro v3 to Astro v4 the following config became invalid:

```ts
import rehypePrettyCode from 'rehype-pretty-code';

// ...

const prettyCodeOptions = {
  theme: 'github-dark-dimmed',
  onVisitLine(node) {
    // Prevent lines from collapsing in `display: grid` mode, and
    // allow empty lines to be copy/pasted
    if (node.children.length === 0) {
      node.children = [
        {
          type: 'text',
          value: ' ',
        },
      ];
    }
  },
  tokensMap: {
    fn: 'entity.name.function',
  },
};

export default defineConfig({
  // https://docs.astro.build/en/guides/markdown-content/#markdown-plugins
  markdown: {
    // ...
    rehypePlugins: [[rehypePrettyCode, prettyCodeOptions]],
  },
}
```

It errors at `rehypePrettyCode, prettyCodeOptions` with the following message:

> Type '[(options?: Options | undefined) => void | Transformer<Root, Root>, { theme: string; onVisitLine(node: any): void; tokensMap: { fn: string; }; }]' is not assignable to type 'string | [string, any] | RehypePlugin<any[]> | [RehypePlugin<any[]>, any]'.
  Type '[(options?: Options | undefined) => void | Transformer<Root, Root>, { theme: string; onVisitLine(node: any): void; tokensMap: { fn: string; }; }]' is not assignable to type '[string, any] | RehypePlugin<any[]> | [RehypePlugin<any[]>, any]'.
    Type '[(options?: Options | undefined) => void | Transformer<Root, Root>, { theme: string; onVisitLine(node: any): void; tokensMap: { fn: string; }; }]' is not assignable to type '[string, any]'.
      Type at position 0 in source is not compatible with type at position 0 in target.
        Type '(options?: Options | undefined) => void | Transformer<Root, Root>' is not assignable to type 'string'.
        
The `rehypePrettyCode` type is declared as follows:

```ts
declare function rehypePrettyCode(options?: Options): void | Transformer<Root, Root>;
```

Can it be turned into something inheriting from Astro's `RehypePlugin` type?

**Comment by o-az** [comment]
What version of rehype-pretty-code are you running? Try it with latest

If you can share a stackblitz example with this issue I will be able to help you faster

**Comment by bennycode** [comment]
Thanks for the quick response. Probably something was odd with my lockfiles. I am using v0.13.1 and I just deleted my `package-lock.json` file, recreated it using `npm i` and now everything is fine. 👍

**Comment by o-az** [comment]
glad to hear!

**Comment by bennycode** [comment]
> glad to hear!

Thank you for your fantastic plugin! I have it in action here: https://typescript.tv/best-practices/filtering-arrays-in-typescript-with-correct-types/
