### ISSUE TITLE
Copy Button css position is not working well.

### ISSUE THREAD

**Issue by taga3s** [rehype-pretty/rehype-pretty-code#240]
When I saw the [document](https://rehype-pretty.pages.dev/plugins/copy-button/#examples) in the mobile screen size and scrolled the code block, I noticed that the copy button is not fixed.

![スクリーンショット 2024-08-28 16 06 17](https://github.com/user-attachments/assets/1ca674e5-6c82-41ea-b859-468a512d41b4)

**Comment by o-az** [comment]
@taga3s thank you for filing this issue!

If you would like to take a shot at fixing please feel free. Here is a copy button example where the position is not misbehaving on horizontal scroll:

https://rehype-pretty-example-next.pages.dev/rsc

the source code for the above code component from the url is here

https://github.com/rehype-pretty/rehype-pretty-code/blob/master/examples/next/src/app/code.tsx

https://github.com/rehype-pretty/rehype-pretty-code/blob/master/examples/next/src/app/rsc/page.tsx

and the source code for the misbehaving one you shared (the docs) is here
https://github.com/rehype-pretty/rehype-pretty-code/blob/master/docs/astro.config.ts#L60

thank you again. I will get to fixing the issue if nobody picks it up.
