### ISSUE TITLE
Pass variable as content in MDX ?

### ISSUE THREAD

**Issue by nekochan0122** [rehype-pretty/rehype-pretty-code#47]
I want to pass a variable to `rehype-pretty-code` as content in MDX,
something like this:

```mdx

```mdx title="Demo.mdx"
{frontmatter.rawmdx}
\```

```

> `frontmatter.rawmdx` is created by `astro-m2dx`

Is It possible?

some imagine syntax:

```mdx

```mdx title="Demo.mdx" content={frontmatter.rawmdx}
\```

```

**Comment by atomiks** [comment]
I don't think metastrings can contain variable content; they're just raw strings.

What we can do is allow a map of the variable content in the options:

```js
const options = {
  contentMap: {
    test: '// comment',
  }
};
```

````md
```js contentKey="test"
```
````

Would this work?

**Comment by atomiks** [comment]
Best option now is just to use a component to pass runtime values (server or client): https://rehype-pretty-code.netlify.app/#react-server-component
