### ISSUE TITLE
Feature request: Fold certain lines

### ISSUE THREAD

**Issue by i-am-the-slime** [rehype-pretty/rehype-pretty-code#86]
It would be nice if it was easily possible to mark certain parts of code examples collapsible (imports in my case) with a little [+] or [-] icon.
Is this something that the `summary` tag could provide or would I have to reach out to radix-ui's collapsible or is it not possible at all?

Sorry if this out of scope!

**Comment by atomiks** [comment]
I'm not sure how to best integrate "interactive" parts into this package. That's why there isn't a copy code button yet either.

**Comment by kudadam** [comment]
@atomiks, torchlight.dev implements this by using the summary tag. Can't we use the same method here. It also uses Shiki by the way

**Comment by o-az** [comment]
This is now a planned feature https://github.com/rehype-pretty/rehype-pretty-code/issues/177
