### ISSUE TITLE
Support for rendering inside a custom component

### ISSUE THREAD

**Issue by manvydasu** [rehype-pretty/rehype-pretty-code#89]
### Goal

I'd like to write MDX file, which contains code examples for multiple languages. In order to reduce amount of space taken by code examples, it would be nice to have dropdown/switch component for toggling between languages. Example screenshot taken from geeksforgeeks

![image](https://github.com/atomiks/rehype-pretty-code/assets/31101065/b55fbeef-2493-496b-8408-239c0d9bfb35)

### Problem
As far as I understand, `rehype-pretty-code` can't currently be used to achieve that as it only exposes a function, which is a a rehype plugin and it can't be used inside a react component.

**Comment by Hi2885** [comment]
> ### Problem
> As far as I understand, `rehype-pretty-code` can't currently be used to achieve that as it only exposes a function, which is a a rehype plugin and it can't be used inside a react component.
>

**Comment by o-az** [comment]
> ### Goal
> 
> 
> 
> I'd like to write MDX file, which contains code examples for multiple languages. In order to reduce amount of space taken by code examples, it would be nice to have dropdown/switch component for toggling between languages. Example screenshot taken from geeksforgeeks
> 
> 
> 
> ![image](https://github.com/atomiks/rehype-pretty-code/assets/31101065/b55fbeef-2493-496b-8408-239c0d9bfb35)
> 
> 
> 
> 
> 
> ### Problem
> 
> As far as I understand, `rehype-pretty-code` can't currently be used to achieve that as it only exposes a function, which is a a rehype plugin and it can't be used inside a react component.
> 
> 
> 
> 
> 
> 

You should be able to do this with Astro Starlight using tabs starlight.astro.build/guides/components/#tabs

`rehype-pretty-code` works well with Asteo in general github.com/atomiks/rehype-pretty-code/tree/master/examples/astro
